### ISSUE TITLE
Elaborate more with usage example

### ISSUE THREAD

**Issue by nwinch** [Nicktho/batch-promises#2]
While minor, perhaps you could elaborate a little more in the doco usage section on whether the iteratee is fired after each promise in the array, or each batch.

Also with the example it doesn't depict that the batching process is in effect.  Perhaps, if a `setTimeout` is to be used then you could add some time comments, like:
```
// batchPromises(2, [1, 2, 3, 4, 5])

// Time: 100ms = 1, 2 (first batch of 2)
// Time: 200ms = 3, 4 (second batch of 2)
// Time: 300ms = 5 (last remaining batch)
// result [1, 2, 3, 4, 5]
```

What do you think?

**Comment by Nicktho** [comment]
Definitely! Want to submit what you have as a PR?

**Comment by Nicktho** [comment]
Fixed with https://github.com/Nicktho/batch-promises/pull/4
