### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by vitaly-t** [Nicktho/batch-promises#8]
I had a bit of a different idea for method [batch](https://github.com/vitaly-t/spex/blob/master/docs/code/batch.md) when I wrote [spex](https://github.com/vitaly-t/spex).

Just sharing ideas... ;)

**Comment by Nicktho** [comment]
Nice.

Though, the original purpose of this library was to limit calls to an asynchronous function, like an api request, for large collections.

**Comment by vitaly-t** [comment]
Ah, for that purpose I wrote method [sequence](https://github.com/vitaly-t/spex/blob/master/docs/code/sequence.md), to be able to iterate through a collection of an unknown size ;)

**Comment by Nicktho** [comment]
Almost, it's like a combination of batch + sequence: "Given a collection, take the next X values, call function Y, if the returned promises all resolve, repeat until there are no next values."

**Comment by vitaly-t** [comment]
That's exactly what method [page](https://github.com/vitaly-t/spex/blob/master/docs/code/page.md) does :)

**Comment by Nicktho** [comment]
Yup that's similar, this method just takes a single collection and splits them up into `pages` for you :)

**Comment by vitaly-t** [comment]
Ok, that implies that the collection is limited? That method `page` works with an unlimited sequence that's split into pages dynamically as you run through the sequence.

**Comment by Nicktho** [comment]
Yeah that's correct, the passed collection is limited, though that limit may not be known. 

```js

getAllTheThings()
.then(things => batchPromises(4, things, doSomethingWithThing))

```

Use cases for this came up in projects where we would query an api that would return an X amount of documents, and then post those up to another service, which had some kind of concurrent connection limiting.

**Comment by vitaly-t** [comment]
Well done! You should some good testing though ;)

Also, I wrote that library to work with any existing promise library :) But i digress.

Cheers!
